version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "82:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        container_name: elasticsearch
        environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'ELASTIC_PASSWORD=userpassword']
        ports: ['127.0.0.1:9200:9200']
        networks: ['stack']

    kibana:
        image: docker.elastic.co/kibana/kibana:6.1.3
        container_name: kibana
        environment:
          - ELASTICSEARCH_USERNAME=kibana
          - ELASTICSEARCH_PASSWORD=userpassword
        ports: ['127.0.0.1:5601:5601']
        networks: ['stack']
        depends_on: ['elasticsearch']
networks: {stack: {}}